# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Build Android
on:
  push:
    branches: [main]
jobs:
  build:
    strategy:
      matrix:
        node-version: [18.x]
        
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      

      - name: Install dependencies
        run: cd servcare && npm install --force
        
      - name: Install React-Native-Cli
        run: cd servcare && npm i -g react-native-cli --force
        
      - name: Build Android Debug
        run: cd servcare && rm -rf android/app/build && react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/ 

      - name: Build Android Apk
        run: cd servcare && cd android && ./gradlew assembleDebug

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: android-debug.apk
          path: servcare/android/app/build/outputs/apk/debug/app-debug.apk
