# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Build Android
on:
  push:
    branches: [main]
jobs:
  build:
    strategy:
      matrix:
        node-version: [18.0.0]
        platform: [ubuntu-latest, macos-latest, windows-latest]
        
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
         node-version: ${{ matrix.node-version }}
         cache: 'npm'

      - name: Install dependencies
        run: npm install --force
        
      - name: Install React-Native-Cli
        run: npm i -g react-native-cli --force
        
      - name: Build Android Debug
        run: rm -rf android/app/build && react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/ 

      - name: Build Android Apk
        run: cd android && ./gradlew assembleDebug

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: android-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
