# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Build Android
on:
  push:
    branches: [main]
  workflow_dispatch:
  
jobs:
  build:
    strategy:
      matrix:
        node-version: [16.x]
        
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: servcare
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
         node-version: ${{ matrix.node-version }}
         cache: 'npm'
         cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run:  npm ci
        
      - name: Install React-Native-Cli
        run: npm i -g react-native-cli
        
      - name: Build Android Debug
        run: rm -rf android/app/build && react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/ 

      - name: Build Android Apk
        run:  cd android && ./gradlew assembleDebug

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: android-debug.apk
          path: servcare/android/app/build/outputs/apk/debug/app-debug.apk

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.SERVICE_USER_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SERVICE_USER_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }} 
          
      - name: Push build to S3
        run: |
         aws s3 sync servcare/android/app/build/outputs/apk/debug/app-debug.apk s3://${{ secrets.S3_BUCKET_DEV }} 
          
          
