name: iOS Debug Build
on:
  push:
    branches: [main]
jobs:
  build:
    strategy:
      matrix:
        node-version: [18.x]
        
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
         node-version: ${{ matrix.node-version }}
         cache: 'npm'

      - name: Install dependencies
        run: npm install --force
        
      - name: Install React-Native-Cli
        run: npm i -g react-native-cli --force
        
      - run: xcode-select -p
        
      - name: Install pod dependencies
        run: |
          cd ios && pod install
        
      - name: Build app
        run: |       
            "xcodebuild \
            -workspace ios/servcare.xcworkspace \
            -scheme servcare \
            clean archive \
            -sdk iphoneos \
            -configuration Debug \
            -UseModernBuildSystem=NO \
            -archivePath $PWD/servcare \
            CODE_SIGNING_ALLOWED=NO"
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: servcare.ipa
          path: ios/build/
        
