name: iOS Debug Build
on:
  push:
    branches: [main]
jobs:
  build:
    strategy:
      matrix:
        node-version: [18.x]
        
    runs-on: macos-latest
    defaults:
      run:
        working-directory: servcare
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
         node-version: ${{ matrix.node-version }}
         cache: 'npm'
         cache-dependency-path: '**/package-lock.json'


      - name: Install dependencies
        run: npm install --force
        
      - name: Install React-Native-Cli
        run: npm i -g react-native-cli --force
        
      - run: xcode-select -p
      
      - name: Xcode version
        run: /usr/bin/xcodebuild -version
        
      - name: Install pod dependencies
        run: |
          cd ios && pod install
          
      - name: Build
        run: xcodebuild -workspace servcare.xcworkspace -configuration Debug -scheme servcare -destination id=1F486764-F318-4FC7-BCC8-70B59676A8FA
        
      - name: Build archive
        run: xcodebuild -sdk iphoneos -project CocoaHeadsNL/CocoaHeadsNL.xcodeproj \
         -configuration Debug  -schema CocoHeadsNL \ 
         -derivedDataPath DerivedData \ 
         -archivePath DerivedData/Archive/CocoHeadsHL archive 
         
      - name: Export Archive
        run: xcodebuild -exportArchive \ 
         -archivePath DerivedData/Archive/CocoHeadsHL.xcarchive \ 
         -exportOptionsPlist provisioning/app-Store.plist \
         -exportPath DerivedData/ipa 

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: servcare.ipa
          path: ios/build/
        
