name: iOS Debug Build
on:
  push:
    branches: [main]
jobs:
  build:
    strategy:
      matrix:
        node-version: [18.x]
        
    runs-on: macOS-latest
    defaults:
      run:
        working-directory: servcare
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
         node-version: ${{ matrix.node-version }}
         cache: 'npm'
         cache-dependency-path: '**/package-lock.json'


      - name: Install dependencies
        run: npm install --force
        
      - name: Install React-Native-Cli
        run: npm i -g react-native-cli --force
        
      - run: xcode-select -p
      
      - name: Xcode version
        run: /usr/bin/xcodebuild -version
        
      - name: Install pod dependencies
        run: |
          cd ios && pod install
        
      - name: Build archive
        run: |
          cd ios && xcodebuild build -workspace servcare.xcworkspace -scheme Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
 

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: servcare.ipa
          path: ios/build/
        
